version: '3.8'

services:
  backend:
    build:
      context: ./backend 
    ports:
      - "3000:3000"  
    depends_on:
      - postgres  
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/patient_db 
    volumes:
      - ./backend:/app 

  postgres:
    image: postgres:13 
    environment:
      POSTGRES_USER: postgres  
      POSTGRES_PASSWORD: password  
      POSTGRES_DB: patient_db  
    ports:
      - "5432:5432" 
